# Generated by Django 4.2 on 2025-04-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Diagnostic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medecin',
            options={},
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='est_active',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='user',
        ),
        migrations.AlterField(
            model_name='medecin',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='specialite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
